# Generated by Django 4.2 on 2023-04-10 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "Code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(default="", max_length=52)),
                (
                    "Continent",
                    models.CharField(
                        choices=[
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("North America", "North America"),
                            ("Africa", "Africa"),
                            ("Oceania", "Oceania"),
                            ("Antarctica", "Antarctica"),
                            ("South America", "South America"),
                        ],
                        default="Asia",
                        max_length=15,
                    ),
                ),
                ("Region", models.CharField(default="", max_length=26)),
                ("SurfaceArea", models.FloatField(default=0.0)),
                ("IndepYear", models.SmallIntegerField(null=True)),
                ("Population", models.IntegerField(default=0)),
                ("LifeExpectancy", models.FloatField(null=True)),
                ("GNP", models.FloatField(null=True)),
                ("GNPOld", models.FloatField(null=True)),
                ("LocalName", models.CharField(default="", max_length=45)),
                ("GovernmentForm", models.CharField(default="", max_length=45)),
                ("HeadOfState", models.CharField(max_length=60, null=True)),
                ("Capital", models.IntegerField(null=True)),
                ("Code2", models.CharField(default="", max_length=2)),
            ],
            options={
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=35)),
                ("District", models.CharField(max_length=20)),
                ("Population", models.IntegerField(default=0)),
                (
                    "CountryCode",
                    models.ForeignKey(
                        db_column="CountryCode",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="world.country",
                    ),
                ),
            ],
            options={
                "db_table": "city",
            },
        ),
        migrations.CreateModel(
            name="CountryLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Language", models.CharField(max_length=30)),
                (
                    "IsOfficial",
                    models.CharField(
                        choices=[("T", "T"), ("F", "F")], default="F", max_length=1
                    ),
                ),
                (
                    "Percentage",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                    ),
                ),
                (
                    "CountryCode",
                    models.ForeignKey(
                        db_column="CountryCode",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="world.country",
                    ),
                ),
            ],
            options={
                "db_table": "countrylanguage",
                "unique_together": {("CountryCode", "Language")},
            },
        ),
    ]
